services:
  magazzino:
    image: ghcr.io/gigiomiccio425/magazzino-zimaos:1.1.1
    container_name: magazzino
    pull_policy: always
    ports:
      # host:container -> apri http://IP-ZIMA:8086
      - "8086:8000"
    environment:
      - APP_PASSWORD=${APP_PASSWORD:-cambiami}   # CAMBIALA
      - APP_NAME=${APP_NAME:-MAGAZZINO}
      - SECRET_KEY=${SECRET_KEY:-}
      - TZ=${TZ:-Europe/Rome}
      - DATA_DIR=/data
    volumes:
      # bind mount su path host ZimaOS (persistenza dati)
      - /DATA/AppData/magazzino:/data
    restart: unless-stopped
